name: Arenagames
version: 1.0.0
description: Custom plugin for ProGaming.
author: Taurhuzz
website: http://taurhuzz.me

main: me.taur.arenagames.Arenagames
database: false

depend: [IdentifierAPI]

commands:
  queue:
    description: Queue related commands.
    aliases: [q]
  player:
    description: Player related commands.
    aliases: [self]
  chat:
    description: Chat channel related commands.
    aliases: [c, ch]
  premium:
    description: Premium related admin commands.
  curr:
    description: Currency related admin commands.
  cash:
    description: Cash related admin commands.
  member:
    description: Member rank set command.
    aliases: [mem]
  mute:
    description: Mute command.
  kick:
    description: Kick command.