name: Arenagames
version: 1.0.0
description: Custom plugin for ProGaming.
author: Taurhuzz
website: http://taurhuzz.me

main: me.taur.arenagames.Arenagames
database: false

depend: [IdentifierAPI]

commands:
  queue:
    description: Queue related commands.
    aliases: [q]
  player:
    description: Player related commands.
    aliases: [self]
  premium:
    description: Premium related commands.
  curr:
    description: Currency related commands.
  cash:
    description: Cash related commands.